# This workflow deletes deployments older than a certain age (7 days by default) in a Vercel project

name: Cleanup Old Deployments

on:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight UTC
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Clean up old deployments
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          # Define the age limit (in days)
          AGE_LIMIT_DAYS=7

          # Get the current date in seconds since epoch
          current_date=$(date +%s)

          # Get the current production deployment
          current_prod_deployment=$(curl -s -X GET "https://api.vercel.com/v6/deployments?projectId=${{ env.VERCEL_PROJECT_ID }}" -H "Authorization: Bearer ${{ env.VERCEL_TOKEN }}" | jq -r '.deployments[] | select(.target == "production" and .state == "READY") | .uid')

          # Get the list of all deployments with their creation times
          deployments=$(curl -s -X GET "https://api.vercel.com/v6/deployments?projectId=${{ env.VERCEL_PROJECT_ID }}" -H "Authorization: Bearer ${{ env.VERCEL_TOKEN }}" | jq -r '.deployments[] | "\(.uid) \(.createdAt) \(.target)"')

          # Convert deployments list to an array
          readarray -t deployments_array <<< "$deployments"

          # Iterate over the deployments
          for deployment in "${deployments_array[@]}"; do
            uid=$(echo $deployment | awk '{print $1}')
            created_at=$(echo $deployment | awk '{print $2}')
            target=$(echo $deployment | awk '{print $3}')
            # Calculate the deployment age in days
            deployment_age_days=$(( (current_date - (created_at / 1000)) / 86400 ))

            # Delete the deployment if it is older than the age limit and not the current production deployment
            if [ $deployment_age_days -gt $AGE_LIMIT_DAYS ] && [ "$uid" != "$current_prod_deployment" ]; then
              echo "Deleting deployment: $uid (Age: $deployment_age_days days, Target: $target)"
              curl -s -X DELETE "https://api.vercel.com/v6/deployments/$uid" -H "Authorization: Bearer ${{ env.VERCEL_TOKEN }}"
            fi
          done
